---
  pkgs:
    - git
    - jq
    - libpython-dev
    - python2.7-minimal
    - python-pip
    - authbind
    - runit
    - curl


  uhp_repo: https://github.com/MattCarothers/uhp
  uhp_version: 1.1.1

  uhp_dir: /opt/uhp
  uhp_user: uhp

  runit_service_dir: /etc/service/uhp

  sysconfig_dir: /etc/default

  uhp_config_dir: /opt/uhp_configs/
